### ISSUE TITLE
App not able to change the image. 

### ISSUE THREAD

**Issue by earlpayton** [dwi336/Eleven#6]
#### Expected behavior
The app is expected to change the image when the option to change image is used in the album section of the music player. 

#### Actual behavior
When the change image option is used for an album, the app isn't able to change the image. 

#### How to reproduce
1. Select a song. 
2. Go to albums 
3. Click on the options menu and press the change image option. 
4. Select an image you wish to apply 
5. The image isn't changed 

* App: Eleven Music Player v1. 0
* Operating system: Android Nought (7.0)
* Device: Motorola moto g5 plus 

#### Recording Of The Bug
![20180314_204423.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521041423/c7zl5jlgsd4vnsiyne67.gif)

    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@earlpayton/app-not-able-to-change-the-image">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by dwi336** [comment]
Hi,

the issue is generated by a race condition storing the album art images. Loading and storing of the image, which should replace the current album image, was implemented asynchronous in a new thread. Before that image can be loaded and stored in the cache, the fragment was updated and the default image is put in the cache. If one image per album is in the cache, trying to store an new image failed. As a workaround loading and setting will be done in the main thread. I think, take some seconds to wait is acceptable.

https://github.com/dwi336/Eleven/commit/7ff65084d245a682777f8911f78aa8c9a70312dd

dwi336

**Comment by dwi336** [comment]
Hi,

change is included in current release:

https://github.com/dwi336/Eleven/releases/download/0.4/Eleven_4.apk

Please test and report, if the workaround will not solve the issue for you.

Thanks.

dwi336

**Comment by b0taSs** [comment]
Can confirm Album image changing to be working in release 0.4
